### ISSUE TITLE
Need .NET Core support

### ISSUE THREAD

**Issue by aborderon** [prash-wghats/vscode-nxunit-test-adapter#1]
Thank you very much.

**Comment by prash-wghats** [comment]
I have not worked with dot net core. There is already a extension for it. https://marketplace.visualstudio.com/items?itemName=formulahendry.dotnet-test-explorer

**Comment by fasetto** [comment]
@prash-wghats I know that other extension. There are lots of bugs and looks like the devs abandoned that project..
This extension seems really nice. But I am using Linux system. So can't use it because of .Net Framework dependency.
.Net Core support would be great.

**Comment by Recodify** [comment]
+1 for dotnet core support. That other extension is super buggy. I use Test Explorer UI for node and python and if this adapter supported dotnet core I could have the same ui across all my projects, which would be lovely!

**Comment by doroudi** [comment]
+1
I really need dotnet core support.

**Comment by m17kea** [comment]
+1

**Comment by doroudi** [comment]
+1

**Comment by m17kea** [comment]
My colleague and I built this [adapter](
https://marketplace.visualstudio.com/items?itemName=derivitec-ltd.vscode-dotnet-adapter).

Needs some work but take a look and feel free to create some issues.
